### ISSUE TITLE
Secure links for password-less login or password reset

### ISSUE THREAD

**Issue by otherjoel** [soegaard/web-tutorial#3]
Thank you for this very instructive tool. I am interested in making a small web app that uses expiring login links sent via email as a way of avoiding the need for passwords. Can you offer any guidance as to how to do this securely from a cryptographic perspective? I.e., is it enough to generate a one-time login token using `crypto-random-bytes`, tack that token onto a login URL as a parameter and check it for expiry when it is used? Would you consider adding a “password reset” feature to the app to illustrate?

**Comment by soegaard** [comment]
Den tir. 15. okt. 2019 kl. 14.15 skrev Joel Dueck <notifications@github.com
>:

> Thank you for this very instructive tool. I am interested in making a
> small web app that uses expiring login links sent via email as a way of
> avoiding the need for passwords. Can you offer any guidance as to how to do
> this securely from a cryptographic perspective?
>
Hi Joel,

What is the flow? Something like this?

    A new user goes to your website and wants to create an account.
    He enters an email.
    You send an email to him containing a token.
    He clicks the link in the email.
    The server checks that the token hasn't expired and logs him in.

I have considered adding a password reset via email to racket-stories.
Although I know how to send emails with Racket using my personal email,
I am afraid to use it for the site. If something goes wrong (say Google
things it is spam),
then my email account may get blocked. So I need to find another email
provider.

It is low-priority for me since Racket Stories is low-traffic. I can easily
reset passwords
manually if there is a need.

/Jens Axel

**Comment by otherjoel** [comment]
>  What is the flow? Something like this?
> A new user goes to your website and wants to create an account. He enters an email. You send an email to him containing a token. He clicks the link in the email. The server checks that the token hasn't expired and logs him in.

Yes exactly this. Users will only ever log in through “magic links” emailed to them.

> I have considered adding a password reset via email to racket-stories. Although I know how to send emails with Racket using my personal email, I am afraid to use it for the site. If something goes wrong (say Google things it is spam), then my email account may get blocked. So I need to find another email provider.

I agree, the mechanics of actually sending the email is a separate problem. I can handle figuring out on my own how to actually send the emails in a reliable, deliverable way using Amazon SES or similar. What I’m most concerned with now is, how do I generate the login links in a secure way? I understand it’s not priority for RS, but if you have any general pointers or approaches it would be much appreciated.

**Comment by soegaard** [comment]
Den tir. 15. okt. 2019 kl. 15.41 skrev Joel Dueck <notifications@github.com
>:

> What is the flow? Something like this?
> A new user goes to your website and wants to create an account. He enters
> an email. You send an email to him containing a token. He clicks the link
> in the email. The server checks that the token hasn't expired and logs him
> in.
>
> Yes exactly this. Users will only ever log in through “magic links”
> emailed to them.
>
Then your idea, sending a link with a unique token with an expiration time
stored on the server, is the way to go.
The solution is only "somewhat secure" though. Anyone with the link
(/token) is able log in to the user account
so we can think of it as a password. Since we are sending it via email, the
security will be as strong as email [1].

[1]  https://www.securedocs.com/blog/how-secure-is-email


> I have considered adding a password reset via email to racket-stories.
> Although I know how to send emails with Racket using my personal email, I
> am afraid to use it for the site. If something goes wrong (say Google
> things it is spam), then my email account may get blocked. So I need to
> find another email provider.
>
> I agree, the mechanics of actually sending the email is a separate
> problem. I can handle figuring out on my own how to actually send the
> emails in a reliable, deliverable way using Amazon SES or similar. What I’m
> most concerned with now is, how do I generate the login links in a secure
> way? I understand it’s not priority for RS, but if you have any general
> pointers or approaches it would be much appreciated.
>

Using `random-crypto-bytes` will be fine.

/Jens Axel

**Comment by otherjoel** [comment]
Thanks!!
